### ISSUE TITLE
Links in README are broken

### ISSUE THREAD

**Issue by eugene-krivobokov** [gradle/test-retry-gradle-plugin#110]
What I see in README.adoc:

```txt
The plugin has been tested with the reporting of link:url[TeamCity, https://www.jetbrains.com/teamcity] and link:url[Jenkins, https://www.jenkins.io].
```

In browser, all links are resolved to `https://github.com/gradle/test-retry-gradle-plugin/blob/master/url`

**Comment by paplorinc** [comment]
Thanks for reporting it @eugene-krivobokov, fixed!
