### ISSUE TITLE
Plugin says it was unable to retry, but it really was

### ISSUE THREAD

**Issue by alvarosanchez** [gradle/test-retry-gradle-plugin#12]
In [this test execution](https://github.com/micronaut-projects/micronaut-cache/runs/390080754) (I have [attached logs just in case they expire](https://github.com/gradle/test-retry-gradle-plugin/files/4062157/buildlogs.txt)), the test `HazelcastClientAsyncCacheSpec.test async cacheable annotations` fails (line 950 in the logs), and is later retried and passes (line 1397).

However, the build ends up failing:

```
Execution failed for task ':cache-hazelcast:test'.
> org.gradle.test-retry was unable to retry the following test methods, which is unexpected. Please file a bug report at https://github.com/gradle/test-retry-gradle-plugin/issues
     io.micronaut.cache.hazelcast.HazelcastClientAsyncCacheSpec#test async cacheable annotations
     io.micronaut.cache.hazelcast.HazelcastClientAsyncCacheSpec#test async cacheable annotations
     io.micronaut.cache.hazelcast.HazelcastClientAsyncCacheSpec#test async cacheable annotations
```

The [retry configuration](https://github.com/micronaut-projects/micronaut-cache/blob/master/build.gradle#L93-L97), and specifically `failOnPassedAfterRetry = false` should have made the build pass, shouldn't it?

The only uncommon part I see here is that [`HazelcastClientAsyncCacheSpec`](https://github.com/micronaut-projects/micronaut-cache/blob/master/cache-hazelcast/src/test/groovy/io/micronaut/cache/hazelcast/HazelcastClientAsyncCacheSpec.groovy) extends from [`AbstractAsyncCacheSpec`](https://github.com/micronaut-projects/micronaut-cache/blob/master/cache-tck/src/main/groovy/io/micronaut/cache/tck/AbstractAsyncCacheSpec.groovy), which is where the tests are defined.

**Comment by breskeby** [comment]
hey @alvarosanchez, 

thanks for the report. I'll have a look and will let you know what I find out.

**Comment by jkschneider** [comment]
@breskeby I think we just need to make this a `Set` rather than `List`? https://github.com/gradle/test-retry-gradle-plugin/blob/master/plugin/src/main/java/org/gradle/testretry/internal/RetryTestResultProcessor.java#L41

**Comment by breskeby** [comment]
@alvarosanchez We found the culprit. The test retry plugin doesn't work well with spocks @Retry annotation. We will fix this and we'll ping you once we released the fix. In the meantime you could also remove the Retry annotation in the abstract class to workaround that issue

**Comment by alvarosanchez** [comment]
Awesome! Looking forward to 1.0.1

**Comment by jkschneider** [comment]
@alvarosanchez 1.0.1 has been released. Thanks for your patience!
