### ISSUE TITLE
Use it with gradle,but it doesn't work

### ISSUE THREAD

**Issue by Yuanshandai** [gradle/test-retry-gradle-plugin#124]
`test {
    retry {
        maxRetries = 5
        maxFailures = 20
        failOnPassedAfterRetry = true
    }
    testLogging.showStandardStreams = false
    maxParallelForks = 6
}`
![image](https://user-images.githubusercontent.com/24652922/146883916-2d5ce2fc-d611-478b-8f8a-1190b099616c.png)

![image](https://user-images.githubusercontent.com/24652922/146883495-6e70e458-6197-4c43-9274-2f7200c67e26.png)

   This is my config,but retry is grey. When I execute  the test cases,I think the config is doesn't work well. It has still failed test cases and I don't see the wrong test cases repeated，Looking forward to recovery

**Comment by marcphilipp** [comment]
Gradle's HTML report isn't yet aware of retries. If you click on one of the classes you should be able to see retried executions. Could you please share a build scan?

**Comment by Yuanshandai** [comment]
Thank you for your reply. The problem has been solved～
