### ISSUE TITLE
Allow setting # times to rerun, regardless of pass/fail status

### ISSUE THREAD

**Issue by melissachang** [gradle/test-retry-gradle-plugin#125]
I'm working on fixing a flaky test. I'd like to run the test 10 times and see how many times fail.

From what I understand, I can't do that with current settings (maxRetries, maxFailures). Say test happens to pass on first run. Then the other 9 runs won't happen.

**Comment by mumrah** [comment]
This would be very useful when "de-flaking" builds. Often times, we encounter tests that are only flaky in CI environments. It would be very useful to re-run a specific test or module N times when trying to diagnose flaky failures.

**Comment by pshevche** [comment]
We discussed this internally and decided that we'd like to keep the plugin focused on retrying only failures. For "retry until failure" use cases, please use features provided by the testing framework used:
* JUnit Jupiter provides [`@RepeatedTest`](https://junit.org/junit5/docs/5.9.1/api/org.junit.jupiter.api/org/junit/jupiter/api/RepeatedTest.html);
* Spock has [`@RepeatUntilFailure`](https://spockframework.org/spock/docs/2.3/all_in_one.html#_repeat_until_failure);
* for JUnit4, you could create a custom `TestRule`, as described [here](https://stackoverflow.com/questions/1492856/easy-way-of-running-the-same-junit-test-over-and-over/28345802#28345802).
