### ISSUE TITLE
Ability to use retry functionality with com.gitlab.et.paralleltests Gradle plugin 

### ISSUE THREAD

**Issue by IlyaHarlamov** [gradle/test-retry-gradle-plugin#129]
I am wondering if it is possible to use `test-retry-gradle-plugin` together with `com.gitlab.et.paralleltests` plugin? It doesn't work by simply putting a retry{} under `test` task.
`paralleltests` plugin is using a `testParallel` task to run the tests.

**Comment by marcphilipp** [comment]
The `paralleltests` plugin does not use a `Test` task. I think you should consider removing the plugin and using the official Cucumber JUnit engine instead which supports [parallel test execution](https://github.com/cucumber/cucumber-jvm/tree/main/junit-platform-engine#parallel-execution) via the regular `Test` task which then would also support retries.

**Comment by IlyaHarlamov** [comment]
@marcphilipp Hi again, maybe you have any example project for Cucumber Junit Platform Engine + Gradle?
I have tried to set it up and run by following the readme on the resource you have shared, although I always get "Test events were not received" when running from IntelliJ.

My setup:
Runner:
```
package testRunners;

import org.junit.platform.suite.api.IncludeEngines;
import org.junit.platform.suite.api.SelectClasspathResource;
import org.junit.platform.suite.api.Suite;

@Suite
@IncludeEngines("cucumber")
@SelectClasspathResource("features") // feature files are located inside resources/features
public class TestRunner{
}
```

In build.gradle:
```
tasks.test {
    useJUnitPlatform()
    systemProperty("cucumber.junit-platform.naming-strategy", "long")
}
```
