### ISSUE TITLE
Junit4 @RunWith(Parameterized.class) - was unable to retry the following test methods

### ISSUE THREAD

**Issue by SergejIsbrecht** [gradle/test-retry-gradle-plugin#13]
Environment:
* Java 8
* Junit 4.12
* org.gradle:test-retry-gradle-plugin:1.0.0
* Gradle 5.4.1.0

Test:
`Test-Class annotated with @RunWith(Parameterized.class)`

```
    test {
        retry {
            maxRetries = 3
            maxFailures = 20
            failOnPassedAfterRetry = false
        }
    }
```

Action:
run tests

Result:
Build fails with 

```
> Task :projectX:test

package.TestX > t1[P1] FAILED
    java.lang.AssertionError at TestX.java:95

package.TestX > t1[P2] FAILED
    java.lang.AssertionError at TestX.java:95

1062 tests completed, 2 failed, 58 skipped

> Task :projectX:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':projectX:test'.
> org.gradle.test-retry was unable to retry the following test methods, which is unexpected. Please file a bug report at https://github.com/gradle/test-retry-gradle-plugin/issues
     package.TestX#t1[P1]
     package.TestX#t1[P2]
```

Expected:
Tests are rerun, and if test-fail-count > configured value => fail build

**Comment by jkschneider** [comment]
Thanks for the report @SergejIsbrecht. Could you show us what the annotation looks like on the `t1` method? We have a [test for parameterized](https://github.com/gradle/test-retry-gradle-plugin/blob/master/plugin/src/test/groovy/org/gradle/testretry/JUnit4FuncTest.groovy#L44) JUnit4 tests that covers at least part of the case, but it seems there is something subtly different about your test that I'm unclear about.

**Comment by jkschneider** [comment]
Feel free to reopen if you can provide more detail @SergejIsbrecht. It may be that your problem was the same as #21 .
