### ISSUE TITLE
Shouldn't it rather be failOnPassedOrSkippedAfterRetry?

### ISSUE THREAD

**Issue by ivans083** [gradle/test-retry-gradle-plugin#130]
If a test is set to be skipped on it's body if certain condition meets, a retried test that is later skipped will fail the build even if failOnPassedAfterRetry = false.
We could either fix and call it failOnPassedOrSkippedAfterRetry
Or add failOnSkippedAfterRetry option in configuration

**Comment by buitcj** [comment]
I also would love this

**Comment by adboyarshinov** [comment]
In my case, tests cases, that have known bugs are marked with special method `knownBUG("BUG-123")`, that set test to skipped and link issue `BUG-123` to report.
So in test report all skipped tests = known bugs.
Problem occurs then fail accidentally happens before `knownBug("BUG-123")`, and in retry successfully reaches this method.

**Comment by pshevche** [comment]
@adboyarshinov , thank you for clarifying the use case. We've discussed it internally, and your proposal makes sense. Let us continue with the PR. Ping me on the PR if you need any help from my side.
