### ISSUE TITLE
1.4.0 is not available in Maven

### ISSUE THREAD

**Issue by adwsingh** [gradle/test-retry-gradle-plugin#135]
I can't see 1.4.0 [here](https://mvnrepository.com/artifact/org.gradle.test-retry/org.gradle.test-retry.gradle.plugin), and 1.3.2 is the latest version.

Can you upload the latest version to maven.

**Comment by marcphilipp** [comment]
1.4.0 is available despite not being listed on that site for some reason:
https://plugins.gradle.org/m2/org/gradle/test-retry/org.gradle.test-retry.gradle.plugin/

Please report this issue to the maintainers of mvnrepository.com.
