### ISSUE TITLE
Compatibility with Gradle 8.0

### ISSUE THREAD

**Issue by marcphilipp** [gradle/test-retry-gradle-plugin#148]
## Motivation

A recent change to internal APIs in Gradle (https://github.com/gradle/gradle/pull/21919) broke compatibility.

A potential solution would be to add a `copy(TestFilter): TestFramework` method to `TestFramework`. Another workaround would be to use reflection to call the old or new constructor.

https://github.com/gradle/test-retry-gradle-plugin/blob/fd1933e424de5d79c1c5c1d18e31896fc0c90380/plugin/src/main/java/org/gradle/testretry/internal/executer/framework/JunitTestFrameworkStrategy.java#L27-L34

**Comment by snoopcheri** [comment]
I had a quick call with @jvandort :
* a copy method on the `TestFramework` level makes the most sense
* we have to see, whether we can define this method on the interface level (depends on required arguments for the specific test frameworks)
* adding `@UsedByScanPlugin("test-retry")` on this additional method is also a very good idea
* @snoopcheri will create a PR and add Justin, Sterling and Marc as reviewers - Justin will possibly add the whole core-team as reviewers

**Comment by snoopcheri** [comment]
Draft PR in gradle/gradle: https://github.com/gradle/gradle/pull/22139
Draft PR in gradle/test-retry-gradle-plugin: https://github.com/gradle/test-retry-gradle-plugin/pull/149
