### ISSUE TITLE
Test results are published after every re-run.

### ISSUE THREAD

**Issue by tyz51** [gradle/test-retry-gradle-plugin#167]
I have got additional functionality to publish test results from custom listener. Now I see that results are published  every re-run. Since this is 'test' task rerun  - new instance of listener is created. 
My question is --->  how can I handle the case if I want to publish report only after all retry happned?

**Comment by marcphilipp** [comment]
You could do it from a finalizer task (which are executed regardless whether the test task failed), e.g. something like this:

```kotlin
val reportTestResults by tasks.registering {
    // ...
}

tasks.test {
    finalizedBy(reportTestResults)
}
```

**Comment by tyz51** [comment]
Thanks @marcphilipp! I'll try and let you know!
