### ISSUE TITLE
Doesn't retry Android Instrumented Tests

### ISSUE THREAD

**Issue by YukiFX** [gradle/test-retry-gradle-plugin#17]
Environment:

- Android project
- Gradle version - 5.2.1
- Android Gradle Plugin Version - 3.2.1
- JUnit version - 4.12
- Runner classes - both AndroidJUnit4 and Parameterized

I have Espresso instrumented tests, but they didn't retry after fail (task: connectedAndroidTest). There were nothing in logs about retry plugin. Part of my app's build.gradle file:
```
plugins {
    id("org.gradle.test-retry") version "1.0.1"
}

tasks.withType(Test) {
    retry {
        failOnPassedAfterRetry.set(true)
        maxFailures.set(10)
        maxRetries.set(3)
    }
}
```

**Comment by schilumula** [comment]
Running in to same issue here. The test retry plugin doesn't work on  Android builds yet

**Comment by dmarjanovic** [comment]
Are there any plans to implement this feature? Many would use it.

**Comment by roman-tikhonov** [comment]
That would be a very helpful feature indeed! In Android world, Android Instrumented Tests are usually the flaky ones, not the regular unit tests.

**Comment by dmarjanovic** [comment]
Any hint into which direction to go? What is the type of Android connected test? Where to look in AOSP source for this? Thanks

**Comment by plezervi** [comment]
Commenting just to +1 this request

**Comment by TurpIF** [comment]
Unfortunately, Android test tasks are not `Test` but `DeviceProviderInstrumentTestTask`. Although, maybe it can be possible to inject a custom [`TestRunnerFactory`](https://android.googlesource.com/platform/tools/base/+/studio-master-dev/build-system/gradle-core/src/main/java/com/android/build/gradle/internal/tasks/DeviceProviderInstrumentTestTask.java#118) inside that will take care of retrying.

**Comment by Syne10** [comment]
hello everyone
how are things going with Android?
is it worth trying?

**Comment by TurpIF** [comment]
Some other Gradle plugin are specialized in this kind of Job.
You may take a look at https://github.com/Banno/Gordon or https://github.com/Malinskiy/marathon.

**Comment by ldaley** [comment]
This is something that we won't be able to do via this plugin. Please raise this feature request for the Android Gradle Plugin. 

https://source.android.com/setup/contribute/report-bugs

**Comment by Haibo-Zhou** [comment]
Is there any news? Instrumented test (UI test) is flaky. We do need retry mechanism for it.

**Comment by cee-dee** [comment]
I'd also be interested in the repetition of a UI test.

**Comment by ryanholden8** [comment]
@Haibo-Zhou @cee-dee Our team is in the same boat. My only suggestion is upvoting and commenting on the open ticket on Google's issue tracker for the issue: https://issuetracker.google.com/issues/239078709
