### ISSUE TITLE
Rerun fails if initial test setupSpec fails 

### ISSUE THREAD

**Issue by jonnybbb** [gradle/test-retry-gradle-plugin#19]
If an errors occurs within the initial test `setupSpec()` in a spock specification the test cannot be rerun.  

```
package acme

class SetupFailureSpec extends spock.lang.Specification {
      void setupSpec() {
           throw new IllegalStateException('Test setup failure')
       }

      def "simpleTest"() {
               expect:
                true
           }
       }
```

Outputs:

```
acme.SetupFailureSpec > classMethod FAILED
    java.lang.IllegalStateException at SetupFailureSpec.groovy:7

1 test completed, 1 failed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> org.gradle.test-retry was unable to retry the following test methods, which is unexpected. Please file a bug report at https://github.com/gradle/test-retry-gradle-plugin/issues
     acme.SetupFailureSpec#classMethod
```

**Comment by ldaley** [comment]
@jjohannes why should such failures cause the tests to be rerun? It's not clear to me that such setup method failures are of a nature that retrying would have any value.

**Comment by ldaley** [comment]
@jjohannes apologies, that was meant for @jonnybbb

**Comment by jonnybbb** [comment]
Test flakyness in such a setup method is a test design smell. Spock's `@Retry` annotation supports rerunning the whole test class in case of any failure in the setupSpec method. Enabling this for the test-retry plugin as well would help people to migrate from `@Retry`.

**Comment by ldaley** [comment]
I'm not convinced that we should add this behaviour. There's not enough justification, and the cost is potentially considerable in that we'll need to add understanding to different types of setup methods. 

I propose that instead we change the plugin to not attempt to retry anything when any _non test_ fails, and just fail.

**Comment by ldaley** [comment]
Superseded by #24
