### ISSUE TITLE
Better support of Gradle report.

### ISSUE THREAD

**Issue by xiakunhou** [gradle/test-retry-gradle-plugin#197]
Since the current report shows the results in a flattened way. Can we enhance the display and make it more user-friendly?
`Each execution of a test is discretely reported in Gradle-generated XML and HTML reports.`

**Comment by pshevche** [comment]
@xiakunhou , have you checked out Build Scans: https://scans.gradle.com/? Here is an example from JUnit of how a flaky test will be visualized: https://ge.junit.org/s/tcwmbmjybjktg/tests/task/:junit-jupiter-engine:test/details/org.junit.jupiter.engine.extension.TimeoutExtensionTests$SeparateThread/oneThreadStuckForeverAndOtherTestsInSameThread()?top-execution=1.

I don't think we will change the format of the XML/HTML report, considering there is a much more superior alternative. But let us know if there is a use-case that is not covered by a Build Scan.
