### ISSUE TITLE
org.gradle.test-retry was unable to retry the following test methods

### ISSUE THREAD

**Issue by Kanti1702** [gradle/test-retry-gradle-plugin#20]
I am utilizing this plugin in gradle with spock test cases.

I have 2 simple test classes, in which 1 test case always fails, and want to re-run that failed test case again.

Stacktrace for error:
at org.gradle.testretry.internal.RetryTestExecuter.failWithNonRetriedTests(RetryTestExecuter.java:88)
	at org.gradle.testretry.internal.RetryTestExecuter.execute(RetryTestExecuter.java:66)
	at org.gradle.testretry.internal.RetryTestExecuter.execute(RetryTestExecuter.java:26)
	at org.gradle.api.tasks.testing.AbstractTestTask.executeTests(AbstractTestTask.java:472)
	at org.gradle.api.tasks.testing.Test.executeTests(Test.java:587)

After analysing your plugin source code , I have found that
          RetryTestResultProcessor.java --> reset() 
method is adding value to nonExecutedFailedTests array. and this reset() method is called from 
          RetryTestExecuter --> execute() 
method after first iteration.

**Comment by jonnybbb** [comment]
@Kanti1702 thanks for reporting and giving it a try. Could you share your the spock tests? Did you tried the latest plugin version 1.0.2 already? We recently releases some fixes addressing spock rerun failures (https://github.com/gradle/test-retry-gradle-plugin/issues/15). We will fix https://github.com/gradle/test-retry-gradle-plugin/issues/20 and https://github.com/gradle/test-retry-gradle-plugin/issues/19 also related to some spock rerun failures soon.

**Comment by Kanti1702** [comment]
@jonnybbb ,
I'm sharing spock test cases:

`package JMockitParallelExecutionTest

import spock.lang.Specification
import spock.lang.Stepwise

@Stepwise
class FirstSpec extends Specification{
	
	def 'API to get message length'(){
		when:
			println "first test ................."
			int length=First.getMessageLength()
		then:
			length==7
	}
	
}`

`package JMockitParallelExecutionTest

import spock.lang.Specification

class SecondSpec extends Specification{

	
	def 'API to get message'(){
		when:
			String message=Second.getMessage()
		then:
			println "second test ................."
			message=="actual method message"
	}
	
}`

build.gradle:
`plugins {
    id 'org.gradle.test-retry' version '1.0.2'
}

apply plugin: 'groovy'
apply plugin: 'java'

repositories {
	mavenCentral()
	maven {
		url "http://repo.fusesource.com/nexus/content/groups/public/"
	}
	maven {
		url "https://repository.jboss.org/nexus/content/groups/public"
	}
	jcenter()
}

dependencies {

	testCompile(
		'org.codehaus.groovy:groovy-all:2.5.8',
		'org.spockframework:spock-core:1.3-groovy-2.5',
		'org.jmockit:jmockit:1.8',
		'junit:junit:4.12'
		)
	testRuntime(
		'cglib:cglib:2.2.2',
		'com.athaydes:spock-reports:1.2.7'
	)
	test{
		testLogging { showStandardStreams = true }
		retry {
			maxRetries = 3
			maxFailures = 20
			failOnPassedAfterRetry = true
    	}
	}
}
`

**Comment by Kanti1702** [comment]
I also found that the combined report shows duplicate test cases which are ran in retry.

**Comment by jonnybbb** [comment]
To make your example run I had to rename the java package name to lowercase and remove the jmockit library. The `test` configuration must be outside of the `dependencies` block. 
I was not able to reproduce your exception.

**Comment by ldaley** [comment]
@Kanti1702 we are unable to reproduce your problem. Please create a sample project that we can execute to reproduce.

**Comment by jkschneider** [comment]
@Kanti1702 feel free to reopen if you can provide any further detail that would allow us to reproduce!
