### ISSUE TITLE
Feature Request: Retry on Success

### ISSUE THREAD

**Issue by pdb-stripe** [gradle/test-retry-gradle-plugin#238]
Can you add a feature to allow retry on success? This would be useful for identifying the reliability of a test (what % does it pass/fail, not simply flaky/failing/passing).

This would likely entail adding a property to the extension, such as `retryOnSuccess` (and potentially `maxSuccesses`), as well as passing this value to the `RetryTestResultProcessor` for use on test runs.

Thanks!

**Comment by pdb-stripe** [comment]
@marcphilipp thanks for the update! Do you have any recommendation for use with JUnit4/Android?

**Comment by marcphilipp** [comment]
I don't think there's a published library for this, but you should be able to achieve the desired behavior using a custom `TestRule`, as described in [this post](https://stackoverflow.com/a/28345802/6327046).

**Comment by pshevche** [comment]
We discussed this internally and decided that we'd like to keep the plugin focused on retrying only failures. For "retry until failure" functionality, please use features provided by the testing framework used.
