### ISSUE TITLE
Behaviour of failure in non test methods is undefined

### ISSUE THREAD

**Issue by ldaley** [gradle/test-retry-gradle-plugin#24]
See https://github.com/gradle/test-retry-gradle-plugin/issues/19. 

For all test frameworks that we support, we need to verify and test the behaviour of failures outside of “test methods”. 

Any such failure should not be subject to retry, but should propagate as a failure.

**Comment by jkschneider** [comment]
@ldaley I'm not sure yet I agree with the conclusion. As @jonnybbb [pointed out](https://github.com/gradle/test-retry-gradle-plugin/issues/19#issuecomment-579618930), the test-retry plugin should act as kind of a "better" Spock `@Retry`, and propagating as failure prevents the substitution of `@Retry` for test-retry. I think this is what he meant?
