### ISSUE TITLE
Failure when retrying Spock test when `failOnPassedAfterRetry = true`

### ISSUE THREAD

**Issue by wolfs** [gradle/test-retry-gradle-plugin#25]
I got `org.gradle.test-retry was unable to retry the following test methods, which is unexpected` when retrying `net.rubygrapefruit.platform.file.WindowsFileEventFunctionsTest#can detect file removed`. See https://github.com/gradle/native-platform/blob/master/build.gradle#L19-L25 and https://e.grdev.net/s/72ekrn4it7gpc/failure?openFailures=WzBd&openStackTraces=WzEsMF0#top=0.

**Comment by jkschneider** [comment]
There is a parameterized test called "can detect #removedAncestry removed" and a non-parameterized test called "can detect file removed". The plugin sees the non-parameterized test failure as an instance of the parameterized name and tries to rerun it instead.
