### ISSUE TITLE
maxFailures behaviour should be per round, not cumulative

### ISSUE THREAD

**Issue by ldaley** [gradle/test-retry-gradle-plugin#3]
I think we should change the implementation, and possibly name, of `maxFailures`. 

The intent is to prevent retrying if there is some kind of systemic failure that is going to cause large numbers of tests to fail. So, it should just consider how many failed executions there are each round and fail if that number is greater than the setting.

The misunderstanding about the semantics makes @tomdcc's point stronger that the name is misleading.
 
Alternatives:

- failureThreshold
- noRetryOnFailedTestCount
- maxAllowedFailuresForRetry

None are great, but the last is my preference

**Comment by jkschneider** [comment]
@ldaley I'm still not totally clear on this. The count should start over on each round in other words? I don't think other names really are any more clear, should just document what the expectation is.
