### ISSUE TITLE
How do I override test results after test run

### ISSUE THREAD

**Issue by IsakovRoman** [gradle/test-retry-gradle-plugin#30]
I have selenide UI tests and they do fail due to various behaviour, that's why I want this plugin to re-run a test N amount of times to make verify was there a bug or not.

There is an option to mark build as successful or failed, but there is no way to mark tests as passed 
in overall results.

I have a job on bamboo to parse JUnit test results and even if test finally was successful, bamboo build fails due to parsing results.

Bamboo logs:

> 10-Feb-2020 16:35:14 | Finished task 'Tests' with result: Success
> 
> 10-Feb-2020 16:35:14 | Starting task 'Parse tests' of type 'com.atlassian.bamboo.plugins.testresultparser:task.testresultparser.junit'
> 
> 10-Feb-2020 16:35:14 | Parsing test results under /home/bamboo/bamboo-agent-home/xml-data/build-dir/Tests...
> 
> 10-Feb-2020 16:35:15 | Failing task since 1 failing test cases were found.

Do you know any workarounds?

**Comment by jkschneider** [comment]
@IsakovRoman Does it fail because the word "FAILURE" was found somewhere in the build log? Is this mechanism parsing the build logs a bamboo feature or something you have written?

**Comment by IsakovRoman** [comment]
@jkschneider . I assume it's internal bamboo junit parser's behaviour. 

parser job fails even if there were a single failed test by design

some additional info

https://stackoverflow.com/questions/18079153/failing-tests-allowed-in-bamboo/18121275

**Comment by alexanderkranga** [comment]
I have the same issue with Jenkins. I have UI tests that I want to retry. I also have `failOnPassedAfterRetry = false` property. When a test passes on second attempt, the first failed attempt is included in JUnit xml report file, for example:

```
<testsuite name="someTestSuiteName" tests="2" skipped="0" failures="1" errors="0" timestamp="2020-02-26T12:15:19" hostname="" time="457.516">
    <properties/>
    <testcase name="someTestName" classname="someTestClass" time="129.797">
        <failure message="org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.cssSelector:.......
        </failure>
    </testcase>
    <testcase name="someTestName" classname="someTestClass" time="64.936"/>
</testsuite>
```
There are 2 tests, 0 skipped and 1 failed. Is there a way to not include failed tests in this report if this test passed on retry?

This causes issues with Jenkins's JUnit report publisher. Even if overall test execution result is PASS (due to `failOnPassedAfterRetry = false`), when JUnit test result publisher collects xml test results, it sees that there is a failed tests, and it marks my build as UNSTABLE, but it should be SUCCESS instead. 

Would be really helpful if we could have an option to ignore failed tests that passed after retry and to not include them in JUnit xml report.

**Comment by vijkris99** [comment]
I echo @alexanderkranga 's views - having the same issue with Jenkins failing the build even when Gradle passes on a retry. It would be nice to have a config key to control the reporting, say, 'reportOnAllRetries' which defaults to true but can be overridden.

**Comment by ldaley** [comment]
This has been reported several times now. What I propose we add is something like:

```
test {
  retry {
    coalesceResultsInXmlReport = true
  }
}
```

When that is set, a finalizer task will be installed that removes any results from the XML that were not the last for the test.

@vijkris99 @alexanderkranga  @IsakovRoman  would that work for you?

**Comment by vijkris99** [comment]
@ldaley That would be perfect, thanks! A tiny nitpick if I may: Could we think of a better name for that option instead of "coalesceResultsInXmlReport"? Perhaps "removeRedundantResultsInXmlReport" or "removeOutdatedResultsInXmlReport" or "removeStaleResultsInXmlReport"?

**Comment by IsakovRoman** [comment]
@ldaley 

Hello, that would be really great! This would work for sure. Big thanks!

Regards,
Roman Isakov.

**Comment by zrkz** [comment]
@ldaley 

Any news when the improvement will be released?

**Comment by ldaley** [comment]
@zrkz I have no ETA at this time.

**Comment by ldaley** [comment]
FYI we are now considering adding this reporting change to Gradle itself instead of doing it via this plugin - https://github.com/gradle/gradle/issues/13115

**Comment by gtach2o** [comment]
Does anyone have a workaround how to keep only the last test execution result in JUnit xml report?

**Comment by Kanti1702** [comment]
Hi @ldaley , Can we have workaround till it's fixed in gradle?

**Comment by SheetalAgrawal28** [comment]
Hi @ldaley I have the same issue with Jenkins. Can we have workaround till it's fixed in gradle?

**Comment by SheetalAgrawal28** [comment]
Hi @ldaley ,  when the fix will be released?

**Comment by Rob-Doherty** [comment]
Just hit the same problem in Jenkins, would be great to have this improvement.

**Comment by himanshukandwal** [comment]
Hi Team, Would be great if this can be released sooner.

**Comment by ldaley** [comment]
Doing this in the plugin itself proved too invasive for people who don't need this feature. Instead, I have added it to Gradle itself and it will be available in the upcoming Gradle 6.8.

The Gradle change is here: https://github.com/gradle/gradle/pull/15130, notably with an explanation of how to use here: https://github.com/gradle/gradle/pull/15130/files#diff-23ed1cf4b4d7e28f4236ae239e1a4546983788d249ac320fec08642240ff3b43R224.

Once that change has been accepted into Gradle, I will close out this issue.

**Comment by ldaley** [comment]
This will be available in Gradle 6.8.

**Comment by ldaley** [comment]
Gradle 6.8-rc-1 is now available.

https://docs.gradle.org/6.8-rc-1/release-notes.html#test-re-run-junit-xml-reporting-enhancements

If anyone is able, early testing of this feature would be appreciated.

**Comment by IsakovRoman** [comment]
@ldaley 

Hello! Thank you for releasing such a feature, going to update right now :)

**Comment by brandenclark** [comment]
@ldaley How does the feature compare between `<testcase>`s to see if there is already an existing `<failure>`? Is it a combination of `classname` and `name`?

I'm trying to make sure this handles parameterized tests (which I think it will) but can't quite track down the comparison logic in your PR: [gradle/gradle#15130](https://github.com/gradle/gradle/pull/15130). Think I've come down with a case of Friday afternoon 🤯 .

**Comment by ldaley** [comment]
@brandenclark it's effectively the combination of `classname` and `name` as reported to Gradle. 

It works fine with parameterised tests, as long as the name is stable (which it should be for other reasons as well).
