### ISSUE TITLE
[Feature request] Possibility to use flag to run tests only in specific environment

### ISSUE THREAD

**Issue by arhont375** [gradle/test-retry-gradle-plugin#33]
We have quite big project that have some number of flaky tests, so we applied this plugin.
The problem is during local development for sure some tests would fail as they not ready yet.
It would be nice if there would be a configuration to configure `retry-test-plugin` to be executed only when specific parameter for Gradle provided (for example only when it running on CI).

**Comment by eriwen** [comment]
Well it is Gradle :) — so you can do something like:

```
test {
    retry {
        maxRetries = System.getenv("CI") ? 2 : 0
    }
}
```

**Comment by ldaley** [comment]
@arhont375 as @eriwen point's out, you can do this yourself relatively easily.

**Comment by arhont375** [comment]
Thank you @eriwen for suggestion.
But contrary to answer from @ldaley even though it's easy to introduce I think such option maybe useful as Retry plugin have much more value in the CI environment compare to local, thus many users may benefit from this.
