### ISSUE TITLE
Ability to easily disable when running in IDE

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/test-retry-gradle-plugin#36]
Is there some way that we could detect that a specific test/class is being run by an IDE and allow users to choose that this plugin should be disabled in that scenario?

Trying to fix some tests after a massive refactor and I'm seeing a lot of the tests re-run when there are failures. This can be fairly annoying when your actively developing in your IDE and you know that a failure is not a symptom of the test being failure.

**Comment by ldaley** [comment]
@JLLeitschuh you can conditionally configure things based on the presence of `System.getProperty('idea.version')`. 

We won't add anything more direct of conventional, at least while this functionality is out as a plugin.

**Comment by JLLeitschuh** [comment]
Might be good to document this perhaps? I'm happy to open a PR.

**Comment by ldaley** [comment]
Sure.
