### ISSUE TITLE
Doesn't retry if return TimeoutException

### ISSUE THREAD

**Issue by vaskocuturilo** [gradle/test-retry-gradle-plugin#39]
Environment:
Gradle 6.2.2
JUnit version - 4.12
Selenium 3.141.59

plugins {
    id 'org.gradle.test-retry' version '1.0.0'
}

test {
    retry {
        failOnPassedAfterRetry = true
        maxFailures = 42
        maxRetries = 1
    }
}

I have Selenium automation scripts, but they didn't retry after fail if Selenium WebDriver return org.openqa.selenium.TimeoutException.

* What went wrong:
Execution failed for task ':test'.
> org.gradle.test-retry was unable to retry the following test methods, which is unexpected. Please file a bug report at https://github.com/gradle/test-retry-gradle-plugin/issues

**Comment by jonnybbb** [comment]
Thanks @vaskocuturilo thanks for reporting. Could you provide a reproducible example of that failure? Some retry issues have been fixed since version `1.0.0` - Could you try out using the latest version `1.1.3` of the plugin
```
plugins {
id 'org.gradle.test-retry' version '1.1.3'
}
```

**Comment by ldaley** [comment]
Hi @vaskocuturilo. If you can, please reopen with a reproducible example that we can use to find the problem.
