### ISSUE TITLE
Test retry plugin can't retry "non-existent" tests

### ISSUE THREAD

**Issue by jduan** [gradle/test-retry-gradle-plugin#40]
Here's an example: 

> org.gradle.test-retry was unable to retry the following test methods, which is unexpected. Please file a bug report at https://github.com/gradle/test-retry-gradle-plugin/issues
>    `x.y.z.AlipayPKCS8CodecTest#initializationError`

I believe the root cause is that when a static initializer fails, none of the tests get to run but Gradle somehow thinks of `initializationError` as a real time name. In other words, the problem may not exist in this plugin. Instead, this plugin suffers from an existing Gradle bug.

**Comment by breskeby** [comment]
@jduan thanks for reporting. We're looking into this. 
Can you provide some details about your test framework and if you use features like parameterized tests or something similar? Is there a chance you can create a small reproducible example? That would make tracing the issue simpler for us.

**Comment by breskeby** [comment]
@jduan I added some test coverage to track the behaviour of exception throwing static intializers. see https://github.com/gradle/test-retry-gradle-plugin/commit/ddd0b7fc8948848092736510fb1691e293cb4081 So far I havn't been able to reproduce the issue you described. A self contained example or some further details would really help a lot

**Comment by ldaley** [comment]
This was fixed by #24.

@jduan please update to version 1.1.0 or later.

**Comment by ldaley** [comment]
@jduan I actually found an issue with flaky custom runners. Could this be what you were running into? If so, will be fixed in upcoming 1.1.5.
