### ISSUE TITLE
Can it be used for non test tasks (e.g. publishing tasks)?

### ISSUE THREAD

**Issue by LouisCAD** [gradle/test-retry-gradle-plugin#42]

**Comment by rpalcolea** [comment]
Personal opinion:

I don’t think this is a good fit for it, publishing has other requirements. For example, if you are uploading a publication and there is a partial publish, let’s say POM was uploaded but JAR wasn’t, retry of the task won’t work as most of repositories are configured to be immutable. You would need write access to delete partial publications and re-publish, which would change between vendors: classic is artifactory vs bintray (different api same vendor). Still you wouldn’t be able to accomplish this with maven central 

Gradle already retries publishing of artifacts when intermittent network issues happen. Here is a PR that added some tests around this https://github.com/gradle/gradle/pull/12127/files

I think it would be nice if at some point there is a contract where you know what has to be uploaded and if something isn’t there, gradle could retry to upload only those files, but that isn’t possible as of today and retrying the publishing task isn’t an option for the immutability reasons 

It would make sense to have such retry at task level if you had a promotion approach where you could upload publications to a staging repo and after some validation in your side, promote it to an immutable one. Then I think retries of the task could be helpful. The promotion story could be great for multi module projects where you need to guarantee everything was published to avoid partial results

**Comment by eriwen** [comment]
No. This would be better done with something else that reacts to the build failing (gradle exit code > 0).

**Comment by LouisCAD** [comment]
@eriwen Is there a way to integrate that in a Gradle task?

@rpalcolea Well, I'm uploading to bintray (which allows re-uploading and can also separate it from effective publishing), and sometimes, I get server issues there like 409 (in other words, it's flaky), that succeed on retry. I just want to CI to retry once or twice on its own in case it happens, to save time when it's a temporary issue, because maintaining open source projects and releasing new versions is already time consuming enough for me to function as a retry monkey.

**Comment by eriwen** [comment]
@LouisCAD You could have a Gradle build that invokes another Gradle build, but honestly I'd just have a publishing bash script like:

(I didn't check the syntax of this)
```
./gradlew publish
if [[ $? != 0 ]];
   ./gradlew publish
fi
```

**Comment by LouisCAD** [comment]
> (I didn't check the syntax of this)

That's the exact reason why I prefer to do it from Gradle with Kotlin code rather than bash: the compiler checks the syntax for me, plus I can then put it in a Gradle plugin if I see myself repeating that across projects.

But I still have no clue what's an appropriate way to do it from Gradle other than maybe running the shell command from it, which I'm not a fan of. Is there a way to run a specific task and get its result or catch any error it produces?
