### ISSUE TITLE
Only retry annotated tests

### ISSUE THREAD

**Issue by andrey-bolduzev** [gradle/test-retry-gradle-plugin#43]
Are there any plans to make the plugin optionally more selective in regards to which tests are being retried, for example by making the plugin config accept an annotation like `@FlakyTest` and only retrying tests annotated with it?

For instance, currently, the plugin is applied module-wide. Let's say I have some tests that are flaky for a reason outside of my control (a bug in a library the project depends on), and I would like to rerun those when they fail. At the same time, I'm afraid of adding new tests that are "flaky" due to an error in my own implementation, and I don't want new tests to be automatically retried only because they are declared in the module the plugin is applied to.

**Comment by markfi-stripe** [comment]
+1 to this feature request. I have a suite of flaky by nature integration tests that I'd like to use this plugin for, however these tests are colocated with non-flaky tests in the same Gradle module.

Being able to configure the retry behavior on a per Test file basis in the source code with an annotation would be great. Even better would be if we could configure retry behavior with a method level annotation on a per test basis.

In addition to the benefit of this being more configurable, this also feels like it would cause less confusion for someone debugging a flaky test. Assuming someone starts diagnosing a flaky test, not even knowing that this plugin is being used at the Gradle scripts level, there is no indication in the test source code that there is any retrying involved -- and the first instinct is probably not to see if this Gradle plugin is installed via the adjacent build scripts.

If there were a `@FlakyTest(maxRetries = 1)` annotation on the test class or method in the source code, it would be very clear that the test is being retried.

In the meantime I will separate my flaky integration tests into a separate module and only use this plugin in that module.

**Comment by asarkar** [comment]
I'd say that in addition to, or as an alternative to, annotations, it's useful to be able to target tests by glob path in the build file. That way, I can target a package or multiple classes at once without having to touch each source file.

**Comment by ldaley** [comment]
The proposed implementation of this is here: https://github.com/gradle/test-retry-gradle-plugin/pull/80

It supports filtering by class name and annotation.

**Comment by ldaley** [comment]
This will be in 1.10.

**Comment by asarkar** [comment]
Thanks, is the documentation updated to show the usage?

**Comment by ldaley** [comment]
@asarkar there is a little here: https://github.com/gradle/test-retry-gradle-plugin#filtering

Please let me know if that's inadequate.
