### ISSUE TITLE
Custom Test task definitions

### ISSUE THREAD

**Issue by helenshin** [gradle/test-retry-gradle-plugin#44]
I have a same question as here: https://stackoverflow.com/questions/60431452/use-gradle-test-retry-plugin-in-custom-test-task-definition

It would be a much appreciated enhancement.

**Comment by dmurat** [comment]
Please, can somebody answer if the retrying of custom test task definitions is supported? If it is, a small example would be much appreciated. Tnx.

**Comment by ldaley** [comment]
Custom tasks are supported. The example on Stackoverflow was configuring the task incorrectly. Please see my reply there.
