### ISSUE TITLE
org.gradle.test-retry was unable to retry the following test methods

### ISSUE THREAD

**Issue by kworam-rally** [gradle/test-retry-gradle-plugin#45]
15:00:03 Execution failed for task ':alm-webapp:testJavaCIpgit'.
    15:00:03 > org.gradle.test-retry was unable to retry the following test methods, which is unexpected. 
        Please file a bug report at 
        https://github.com/gradle/test-retry-gradle-plugin/issues
    15:00:03      com.f4tech.slm.persistence.domain.change.ObjectAttributeChangeRecycleBinIntegrationTest#recycleWorkProductTest[0](com.rallydev.TestPersistenceContext@31c6bead)

```
public class ObjectAttributeChangeRecycleBinIntegrationTest extends UserStoryTestWithParameters {
...
        // this test method is not annotated
        public void recycleWorkProductTest(TestPersistenceContext context) throws Exception {
```

**Comment by jonnybbb** [comment]
@kworam-rally thanks for reporting. Could you provide an example to reproduce the problem. What framework are you using for those parameterized Tests?

**Comment by ldaley** [comment]
Closing as stale.
