### ISSUE TITLE
Plugin doesn't work if tests are executed in parallel 

### ISSUE THREAD

**Issue by dengayevskiy-sb** [gradle/test-retry-gradle-plugin#46]
Hi guys! Unfortunately plugin doesn't work if I enable parallel test execution in JUnit.
https://junit.org/junit5/docs/snapshot/user-guide/#writing-tests-parallel-execution

I'm using plugin version 1.1.5 and JUnit 5.6.2.

**Comment by jonnybbb** [comment]
Thanks @dengayevskiy-sb for reporting - could you please provide an executable example to reproduce the issue

**Comment by ldaley** [comment]
Closing as stale.
