### ISSUE TITLE
Specifying Retries in `build.gradle.kts`

### ISSUE THREAD

**Issue by aryeh-looker** [gradle/test-retry-gradle-plugin#47]
I'm converting a gradle file from Groovy to Kotlin and am curious how to convert the following:

```
    tasks.named<Test>("test") {
      // from Groovy, does not compile
      retry {
          // Max number of failures in the initial test run at which to not attempt retrying as the build is likely broken
          maxFailures = 10
          maxRetries = 1
      }
    }
```

I did also notice this, but it is not quite applicable, though similar:

https://github.com/gradle/test-retry-gradle-plugin/blob/1def59cf2f2c7db637f97c332b2a410fe0f65da5/samples/sample-junit5/build.gradle.kts#L23

**Comment by ldaley** [comment]
Hi @aryeh-looker you need to use `maxFailures.set(10)`.

**Comment by dima74** [comment]
@ldaley could you please add example with `build.gradle.kts` to `README`

**Comment by ldaley** [comment]
@dima74 sure thing. Done.
