### ISSUE TITLE
junit5 sample test fails after non initial execution

### ISSUE THREAD

**Issue by ldaley** [gradle/test-retry-gradle-plugin#5]
The sample project tests leave a marker file that never gets cleaned up, so if you run the sample test more than once it fails.

**Comment by jkschneider** [comment]
There's not an easy alternative I can think of. The IDE forks the JVM for each test run, Gradle does not by default. Placing the marker file in a temp directory even when it is done in a static way is insufficient. A similar static marker of any other sort would have the same issue. I don't consider this worth investing a significant amount of time with?

**Comment by jkschneider** [comment]
Best we can do I think is to delete the marker in `tasks.test { doFirst { ... } }`
