### ISSUE TITLE
Flaky tests are only marked as skipped (not passed)

### ISSUE THREAD

**Issue by caseyduquettesc** [gradle/test-retry-gradle-plugin#51]
Looking at the screenshots in the readme, I was expecting a flaked test to be marked as failed, retry up to _N_ times, until the plugin gives up because it reached the retry limit or the test passed.

What I am observing is the first failure is marked correctly, but every retry is marked as skipped regardless of whether it passes or fails. The plugin still works correctly though, failing the task if the test doesn't pass and passing the task if the flaky test ultimately succeeds, it just doesn't show up that way in the test report or in the build script hooks for `afterTest` and `afterSuite`.

This makes it a little difficult for someone unfamiliar with how many retries are configured to know if the test passed or not because all you can see is failed and skipped (or ignored in the html report). We have a bit of logic to report on flaked tests in the `afterTest` configuration but found that it can't work without also knowing how many retries are configured and then tracking how many times the test is called. 

Let me know if there's anything more I can provide to help diagnose what might be happening.

Gradle 5.6.4
org.gradle:test-retry-gradle-plugin:1.1.6
Junit 4.1.2

Here is a flaky test I took from your announcement blog post that fails and then succeeds.

![image](https://user-images.githubusercontent.com/16676170/85187972-954dee00-b258-11ea-84c0-fb5dec692434.png)

Here is console output from the same test, generated by our `afterTest` configuration, which I see now actually does include 1 success and 1 failure and 0 skips at the suite level. Note: Even though the suite result says Failed, the test task itself did correctly succeed.

![image](https://user-images.githubusercontent.com/16676170/85187996-ba426100-b258-11ea-8db8-96cae06d1688.png)

Here is a simplified version of our `afterTest` and `afterSuite` configurations

```groovy
afterTest { desc, result ->
    def duration = System.currentTimeMillis() - clock
    println "Performed test [${desc.className}] -- ${desc.name} with result: ${result.resultType} in ${duration}"                
}

testLogging.showStandardStreams = false
afterSuite { desc, result ->
    if (!desc.parent) { // will match the outermost suite
        println "Results: ${result.resultType} (${result.testCount} tests, ${result.successfulTestCount} successes, ${result.failedTestCount} failures, ${result.skippedTestCount} skipped)"
    }
}
```

And forgot to add the plugin configuration

```groovy
allprojects {
    apply plugin: "org.gradle.test-retry"

    tasks.withType(Test).configureEach {
        retry {
            // Whether tests that initially fail and then pass on retry should fail the task.
            failOnPassedAfterRetry.set(System.getenv().containsKey("RUN_ALL_TESTS"))

            // The maximum number of test failures that are allowed before retrying is disabled.
            maxFailures.set(30)

            // The maximum number of times to retry an individual test.
            maxRetries.set(5)
        }
    }
}
```

1. Could you help me understand why my html report doesn't align with the example report in the readme (fail/ignore vs fail/pass)?
2. How come the test result for all retries is SKIPPED?

Thanks for the great plugin

**Comment by caseyduquettesc** [comment]
Interestingly, while the `resultType` doesn't appear accurate, the result type counts _are_. After each test, I included `result.getSuccessfulTestCount()`, `result.getFailedTestCount()`, and `result.getSkippedTestCount()`.

Iteration 1 shows a failure count of 1
Iteration 2 shows a successful count of 1

```
Performed test [com.snapchat.time.RerunTest] -- flakyTest with result: FAILURE in 15
success count: 0, failure count: 1, skipped count: 0
FAILURE

com.snapchat.time.RerunTest > flakyTest FAILED
    java.lang.IllegalStateException: Rerun me!
        at com.snapchat.time.RerunTest.flakyTest(RerunTest.java:13)
Performed test [com.snapchat.time.RerunTest] -- flakyTest with result: SKIPPED in 1
success count: 1, failure count: 0, skipped count: 0
SKIPPED
Flaky test detected com.snapchat.time.RerunTest.flakyTest
Results: FAILURE (2 tests, 1 successes, 1 failures, 0 skipped, 1 flaky)

2 tests completed, 1 failed
```

**Comment by ldaley** [comment]
Hi @caseyduquettesc.

I'm not able to reproduce what you're seeing. If you can create a project that reproduces the behaviour, please upload it here and reopen the issue.
