### ISSUE TITLE
Test that are skipped after failing are considered to have passed

### ISSUE THREAD

**Issue by ldaley** [gradle/test-retry-gradle-plugin#52]
This is unlikely to match the user's intention.

Such a scenario should not be considered success. Whether tests that are skipped after failure should be retried until retries are exhausted is a separate question. It might be better to stop as soon as this situation is encountered.

**Comment by marcphilipp** [comment]
> It might be better to stop as soon as this situation is encountered.

I tend to agree.

**Comment by jonnybbb** [comment]
So the build should fail for a case where a test would `FAIL` in the first run. `SKIPPED` in the first retry and finally would have `PASSED` in the second retry run, since the retry should better stop in such a situation?

**Comment by marcphilipp** [comment]
I think so but we should retry other failed tests and fail in the end.

**Comment by jonnybbb** [comment]
Keep retrying `FAIL` and then `SKIPPED` tests - seems to me a simpler approach. @ldaley / @marcphilipp I am not sure if we should stop retrying those tests in such a situation. Can you give me some more context why retrying should be stopped?

**Comment by ldaley** [comment]
@jonnybbb “simpler” for who? If you mean in terms of implementation, that's the wrong perspective. 

I can't imagine a situation where we would get FAILED, SKIPPED, PASSED. So, why continue? That said, I don't feel strongly. I can buy the argument that treating SKIPPED as FAILED in a retry context presents “simpler” behaviour to users. Let's just go with that.

**Comment by jonnybbb** [comment]
My intention was not to propose a "simpler" solution at the expense of the "right" solution. Depending on how `@IgnoreIf` or `assumeThat()` that result in SKIPPED test is used, there might be rare cases out there resulting in such a FAILED, SKIPPED, PASSED scenario. 
I agree with your proposal. The PR https://github.com/gradle/test-retry-gradle-plugin/pull/59 is ready for review.
