### ISSUE TITLE
Retries run only in single thread with TestNG

### ISSUE THREAD

**Issue by AliaksandrHaurylau** [gradle/test-retry-gradle-plugin#55]
I have a TestNG suite with parallel='methods' and threads=5 settings and retry plugin wrapped around
Tests run in parallel, but then failed ones retries one-by-one

I found statement about TestNG compatibility, but no explcit mention regarding parallel tests execution - is it possible?
(I'm using TestNG 6.4.13, gradle 6.5.1 and plugin version is 1.1.6)

**Comment by bigdaz** [comment]
@AliaksandrHaurylau this should be fixed in v1.1.8, just released. Could you please try it out and confirm if this issue remains for you?
