### ISSUE TITLE
Preserve modulePath parameter when wrapping JvmTestExecutionSpec

### ISSUE THREAD

**Issue by jjohannes** [gradle/test-retry-gradle-plugin#57]
Update this code:
https://github.com/gradle/test-retry-gradle-plugin/blob/069fdbee808c403d191833673916ed31767c01fc/plugin/src/main/java/org/gradle/testretry/internal/RetryTestExecuter.java#L103-L117

To use this constructor:
https://github.com/gradle/gradle/blob/90c649a30f617acae4fa4fc8445e95977bfbc4d7/subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/JvmTestExecutionSpec.java#L51

Otherwise the modulePath would not be forwarded correctly when testing a Java module. This can be reproduced when doing test retry in projects like these:
https://github.com/gradle/gradle/blob/8530026fec596904e8ce2c91ec4354e717fe5128/subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/jpms/test/JavaModuleBackboxTestExcutionIntegrationTest.groovy

It is only an issue when using Gradle 6.4+, in a project where `modularity.inferModulePath.set(true)` and where the test source set itself is a Java module (like in `JavaModuleBackboxTestExcutionIntegrationTest` linked above).

**Comment by bigdaz** [comment]
I guess we'll need to use version detection or reflection to continue to support older versions of Gradle.

**Comment by jjohannes** [comment]
Right. We kept the old constructor around in Gradle for the time being. So code against the old one would still compile.

If you are fine to build this plugin with at least Gradle 6.4, you could do a Gradle version check for `>= 6.4`. And call one of the two constructors based on that. Then there is no need to use reflection.
