### ISSUE TITLE
failFast test property is ignored 

### ISSUE THREAD

**Issue by jonnybbb** [gradle/test-retry-gradle-plugin#61]
If the `failFast` test property is set to `true` it is ignored by the test-retry plugin and the subsequent tests after the first test failures are executed nevertheless although they are marked as `SKIPPED`. 

```build.gradle
test {
    failFast = true
    retry {
        maxRetries = 1
        maxFailures = 2
    }
    testLogging {
        events "passed", "skipped", "failed"
    }
}
```

```
@Unroll
@Stepwise
class TestRetrySkippedSpec extends Specification {

    def "test 1 [#v]"() {
        expect:
        FlakyAssert.flakyAssert()

        where:
        v << ['a', 'b']
    }

    def "test 2"() {
        expect:
        assert false : "I should not have been executed if failFast is true"
    }
}
```

 
Build scan: https://scans.gradle.com/s/rjxkl5n7dhytw/tests/:test/org.gradle.customers.example.TestRetrySkippedSpec/test%202#1

**Comment by ldaley** [comment]
@jonnybbb I'm not sure about this. What I observe is that after the failure everything is skipped. The problem seems to be that we attempt retry after the fail fast has stopped us, when there is no need.

**Comment by ldaley** [comment]
Superseded by https://github.com/gradle/test-retry-gradle-plugin/issues/75
