### ISSUE TITLE
Errors/Exceptions from classMethods are handled quietly and marked as FAILED instead of FLAKY

### ISSUE THREAD

**Issue by fdaca** [gradle/test-retry-gradle-plugin#65]
#### Stack

- ScalaTest 3.0.8
- test-retry-gradle-plugin 1.1.3
- Gradle 5.6
- Gradle Enterprise 2020.2.1

#### Description

When an exception is thrown outside the test code, i.e. in `beforeEach` clause, the run is repeated by the plugin, but the resulting output in console and Gradle Enterprise is misleading:

1. In console log, the build results as `SUCCESS`, although it shows error/exception log and a summary with failure count `2 tests completed, 1 failed` without any information about flakiness or retries.
2. In Gradle Enterprise, the build result is `SUCCESS`, but the test is marked as `FAILED` instead of `FLAKY` - also without any information about retries.

**This made us debug for a potential situation (stopped execution before build status update i.e. `System.exit(..)`) where build is wrongly marked as successful despite occurring errors.** Reproducing the issue shows that was not the case - it's basically the retry plugin doing retry quietly and succeeding in next run.

The behaviour for regular test failures is understandable since those appear as `FLAKY` in Gradle Enterprise. Although it's hard to process the output of builds with failing classMethods.

#### Code Example

```scala
"DummyProtocolHandler" should {
  "respond to ping with pong" in {
    val dummyProtocolHandler = new DummyProtocolHandler()
    dummyProtocolHandler.ping() should be("pong")
  }
}

override def beforeEach(): Unit = {
  val rnd = new scala.util.Random

  if (rnd.nextBoolean()) {
    throw new TimeoutException("custom timeout")
  }
}
```

#### Example result

```
> Task :dummy:test
Picked up _JAVA_OPTIONS: -Djava.awt.headless=truecom.sumologic.dummy.DummyProtocolHandlerTest > classMethod FAILED
    java.util.concurrent.TimeoutException: custom timeout
        at com.sumologic.dummy.DummyProtocolHandlerTest.beforeEach(DummyProtocolHandlerTest.scala:24)
        at org.scalatest.BeforeAndAfterEach.runTest(BeforeAndAfterEach.scala:220)
        at org.scalatest.BeforeAndAfterEach.runTest$(BeforeAndAfterEach.scala:214)
        at com.sumologic.dummy.DummyProtocolHandlerTest.runTest(DummyProtocolHandlerTest.scala:9)
Picked up _JAVA_OPTIONS: -Djava.awt.headless=true2 tests completed, 1 failed
There were failing tests. See the report at: file:///Users/fdaca/git/sumo/dummy/build/reports/tests/test/index.html
> Task :dummy:test DONE
```

<img width="744" alt="Screenshot 2020-08-12 at 12 27 11" src="https://user-images.githubusercontent.com/56257571/90005261-3b393a00-dc97-11ea-8060-a3006bd4de44.png">

<img width="742" alt="Screenshot 2020-08-12 at 12 28 13" src="https://user-images.githubusercontent.com/56257571/90005315-50ae6400-dc97-11ea-9807-7e648112b6c8.png">

#### Solution idea

It would be great if the plugin could be more verbose about the retries and give clearer output for console and Gradle Enterprise - especially for classMethod failures. Also it could somehow connect successful runs with failed ones - at least by flagging failed runs that cause retry with as *will retry*.

**Comment by ldaley** [comment]
This has been fixed for JUnit based tests. 

A fake passed event is emitted when such a lifecycle failure occurs, but then does not occur on retry. This will allow tooling to perceive it as flaky in the same way as non-lifecycle failures.
