### ISSUE TITLE
Retries fail with TestNG tests that use parameters without toString() methods

### ISSUE THREAD

**Issue by ghale** [gradle/test-retry-gradle-plugin#66]
If a TestNG test method specifies a `dataProvider` that returns parameters that are objects without `toString()` methods, the test method ends up with the object id in its name, e.g. `test[1](acme.ParameterTest$Foo@40256d59)`.  When the test is retried, a new parameter object is created with a different id, creating a different method name.  After the retry run, the plugin thinks that the method from the first execution was not retried because of the name mismatch and throws an exception:
```
Execution failed for task ':test'.
> org.gradle.test-retry was unable to retry the following test methods, which is unexpected. Please file a bug report at https://github.com/gradle/test-retry-gradle-plugin/issues
     acme.ParameterTest#test[1](acme.ParameterTest$Foo@40256d59)
```

One option to fix this might be to change the `TestMethodDescriptor` to capture this data separately (rather than all in the test method name) and then uniquely identify the test based on only the method name and iteration index (disregarding the parameter data).  This would likely require a TestNG-specific implementation of `TestMethodDescriptor` and changes on the build tool side.

Another option might be to just recognize the pattern in the test method name and parse it on the retry side.  Then we would only take into account the test name and iteration index when identifying the test.

Or we could just say that parameter `toString()` representations have to be consistent across builds for the same parameter and that we don't support retries for parameters that don't meet this requirement.  If this is the case, though, I think we should identify when this is the case and provide a better error message with information on how to remediate the problem.

**Comment by ghale** [comment]
It looks like we are already parsing and stripping off the parameterized segment of the test name when we submit the test on retry, so I'm inclined to use that same mechanism here.

**Comment by ldaley** [comment]
@ghale I don't quite understand the ins and outs, but generally speaking we use the practice of retrying all permutations of a test with a failed permutation in other places so that would be a reasonable solution. 

If you have an idea on how to go about this in this case then I suggest going ahead and submitting a PR.
