### ISSUE TITLE
Unable to retry test methods

### ISSUE THREAD

**Issue by MikeTurpinSDG** [gradle/test-retry-gradle-plugin#73]
I'm encountering an unexpected error and I'm not certain how to resolve/debug the error.    Source code to replicate the error is at: https://github.com/MikeTurpinSDG/GradleTestRetryPluginTests

A scan of the issue is at: https://scans.gradle.com/s/susx3mimb4bfe

Gradle 5.6.4
org.gradle:test-retry-gradle-plugin:1.1.9

The error happens when attempting to retry two tests that are intentionally random at their failures.  One item to note when running the tests, the exact errors will switch between: 
<pre><font color="#CC0000"><b> Task :pipelineTests</b></font><font color="#CC0000"> FAILED</font>

<font color="#CC0000">FAILURE: Build failed with an exception.</font>

* What went wrong:
Execution failed for task &apos;:pipelineTests&apos;.
<font color="#C4A000">&gt; </font>org.gradle.test-retry was unable to retry the following test methods, which is unexpected. Please file a bug report at https://github.com/gradle/test-retry-gradle-plugin/issues
     Pipeline.RandomFlakyTestSimulatorSpec#SimulateFlakyTestOdd1
     Pipeline.RandomFlakyTestSimulatorSpec#SimulateFlakyTestOdd2
</pre>
and
<pre><font color="#CC0000"><b> Task :pipelineTests</b></font><font color="#CC0000"> FAILED</font>

<font color="#CC0000">FAILURE: Build failed with an exception.</font>

* What went wrong:
Execution failed for task &apos;:pipelineTests&apos;.
<font color="#C4A000">&gt; </font>org.gradle.test-retry was unable to retry the following test methods, which is unexpected. Please file a bug report at https://github.com/gradle/test-retry-gradle-plugin/issues
     Pipeline.RandomFlakyTestSimulatorSpec#SimulateFlakyTestEven2
     Pipeline.RandomFlakyTestSimulatorSpec#SimulateFlakyTestEven1
</pre>
This is expected random failures and the error happens for either test result set.

Please let me know any additional information I can provide or steps I might take to try and advance with debugging the error myself.

As a side note,  the test-retry-gradle-plugin doesn't have sources/javadoc files published (at least that I could find) and so I wasn't able to step through the plugin to try and diagnose the issue directly.  From looking at https://plugins.gradle.org/m2/org/gradle/gradle-hello-world-plugin/0.2/ and https://github.com/gradle/gradle-hello-world-plugin/blob/master/build.gradle it looks like the tasks were never added to publish those items.

**Comment by ldaley** [comment]
I expect the issue here is some kind of incompatibility with Spock's include mechanism.

**Comment by ldaley** [comment]
This is a Spock bug. It can't handle test filtering for the package `Pipeline`. If you change this to `pipeline`. It works. Please take this up with the Spock team.

Note that this also prevents any kind of test filtering/targeting, such as running specific tests via Intellij IDEA.
