### ISSUE TITLE
Add support for combination of failFast and retrying

### ISSUE THREAD

**Issue by JohnRambo** [gradle/test-retry-gradle-plugin#75]
Currently if `failFast` is set to `true` it will override the retrying policies. That is, in the event of a test failure the test task will finish abruptly after the first test failure, that failure will not be retried and all remaining tests will not be run.

It is desirable in certain scenarios to have a fast failure signal but still avoiding noise from flaky tests. Ideal solution for such purpose would retry the failing test immediately after it failed up to `maxRetries` times. If these retries fail the test task should fail immediately, if it succeeds we would proceed with running the reminder of the tests.

**Comment by ldaley** [comment]
Thanks @JohnRambo. 

For the cases where everything ultimately passes, this is going to be slower. It's going to take time to stop any in-flight tests on the first failure, and ultimately running the “rest” is going to incur the cost of another JVM to run them. However, if you really want fail fast behaviour I can see how it could be worth it.

**Comment by ldaley** [comment]
I tried to implement this in this plugin, but it's not possible due to the way the task is wired up. It will need to be implemented in Gradle itself. I have raised https://github.com/gradle/gradle/issues/15175 for that.
