### ISSUE TITLE
org.gradle.test-retry was unable to retry the following test methods, which is unexpected. Please file a bug report 

### ISSUE THREAD

**Issue by virenderg** [gradle/test-retry-gradle-plugin#76]
test-retry plugin fails to retry end2end tests. Getting:
19:43:50       com.test.forms.FormEnd2EndTestGetList#initializationError
19:43:50       com.test.forms.FormEnd2EndTestPatch#executionError
19:43:50       com.test.forms.FormResponseEnd2EndTestPatch#executionError
19:43:50       com.test.forms.FormResponseEnd2EndTestUpdateFileId#executionError

Is there a way to get more info on what is failing?

**Comment by marcphilipp** [comment]
Could you please post the entire error message?

**Comment by virenderg** [comment]
I ran it on Jenkins using gradle 6.5 and JUnit 5. Only message (outside of tests themselves) I got was: 
20:21:13  FAILURE: Build failed with an exception.
20:21:13  
20:21:13  * What went wrong:
20:21:13  Execution failed for task ':end2endTest'.
20:21:13  > org.gradle.test-retry was unable to retry the following test methods, which is unexpected. Please file a bug report at https://github.com/gradle/test-retry-gradle-plugin/issues
20:21:13       com.test.forms.v3.m1.FormEnd2EndTestGetList#initializationError
20:21:13       com.test.forms.v3.m1.FormResponseEnd2EndTestPatch#executionError
20:21:13  
20:21:13  
20:21:13  * Try:
20:21:13  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
20:21:13  
20:21:13  * Get more help at https://help.gradle.org
20:21:13  
20:21:13  Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
20:21:13  Use '--warning-mode all' to show the individual deprecation warnings.
20:21:13  See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by marcphilipp** [comment]
Which version of the test-retry plugin are you using?

**Comment by virenderg** [comment]
id 'org.gradle.test-retry' version '1.1.9'

**Comment by virenderg** [comment]
useJUnitPlatform

**Comment by virenderg** [comment]
Saw a strange behavior, adding retry settings in tasks.withType(Test) {} instead of end2endTests resolved this issue for us. Not sure if there is a difference in a way plugins are loaded.
