### ISSUE TITLE
Retry not working when test class annotated with @UseDataProvider

### ISSUE THREAD

**Issue by eugeniomauri** [gradle/test-retry-gradle-plugin#77]
If a JUnit 4 test class has class annotation 'UseDataProvider'ex:
```
    @UseDataProvider(
            value = "blabla",
            location = RequestDataProvider.class
    )
   @Test

```
...then the retry mechanism does not work. 
Only one retry is attempted but it finished immediately with this error:

Gradle Test Executor 1 finished executing tests.
Gradle Test Executor 2 started executing tests.

> Task :runATest
Starting process 'Gradle Test Executor 2'. Working directory: /etc....etc... 
Command: /.....etc.../java -DBROWSER=chrome -Dlots..of...parameters...etc... -javaagent:/Users/i315012/.gradle/caches/modules-2/files-2.1/org.aspectj/aspectjweaver/1.8.10/e198c5fee28988c355f74e06461614eae36b2032/aspectjweaver-1.8.10.jar @/private/var/folders/n5/8v780bbj349cpgpwrpf5b7kh0000gn/T/gradle-worker-classpath15329141361022166370txt -Xmx512m -Dfile.encoding=utf-8 -Duser.country=US -Duser.language=en -Duser.variant -ea worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 2'
Successfully started process 'Gradle Test Executor 2'

Gradle Test Executor 2 finished executing tests.

> Task :runATest FAILED

1 test completed, 1 failed

* What went wrong:
Execution failed for task ':runATest'.
> org.gradle.test-retry was unable to retry the following test methods, which is unexpected. Please file a bug report at https://github.com/gradle/test-retry-gradle-plugin/issues
     ...full..domain....CompanyTokenAPITestSuite#externalValidation[0: ...full..domain.....DataModelObj2@3235e4f0, ...full..domain....DataModelObj2@2daaf12e]

**Comment by ldaley** [comment]
I was able to get retry working with a test using `@UseDataProvider`. If you can, please reopen and attach a reproducible test case.
