### ISSUE TITLE
Add timeout config for re-run

### ISSUE THREAD

**Issue by arturmkr** [gradle/test-retry-gradle-plugin#82]
It would be great to have ability to specify timeout for retry.

For example:
retryTimeout = 10 seconds 
Than if test is failed, next re-run would be in 10 seconds.

**Comment by ldaley** [comment]
@arturmkr can you expand on why/when you would use this please.

**Comment by arturmkr** [comment]
The reason, why I use test retry plugin it's environment issues, that can take place during ui functional tests.

Approximately each hour, my environment either works too slow, either doesn't respond for about 10 seconds.

Test retry plugin restarts tests immediately. As a result, retry doesn't always help and tests are failed.

**Comment by ldaley** [comment]
At this time, we aren't going to add this functionality. The rationale is that this plugin should not be used as the primary means for stabilising tests, but rather as a means for identifying flakiness. Dealing with unreliable external dependencies should be pushed down to the test logic.

While adding a delay could also be a benefit for detection, we don't have quite enough evidence that introducing the delay would be worth it. If more opinions/cases arise we can certainly revisit.
