### ISSUE TITLE
Unable to retry @BeforeClass method

### ISSUE THREAD

**Issue by deepy** [gradle/test-retry-gradle-plugin#84]
We're using TestNG and test-retry-gradle-plugin which in general works good, but I'm seeing a bunch of failures like this which are asking us to report a bug.
```
Caused by: java.lang.IllegalStateException: org.gradle.test-retry was unable to retry the following test methods, which is unexpected. Please file a bug report at https://github.com/gradle/test-retry-gradle-plugin/issues
    com.example.OurTestClass#beforeClass

at org.gradle.testretry.internal.executer.RetryTestExecuter.failWithNonRetriedTestsIfAny(RetryTestExecuter.java:119) |
at org.gradle.testretry.internal.config.TestTaskConfigurer$FinalizeTaskAction.execute(TestTaskConfigurer.java:109) |  
at org.gradle.testretry.internal.config.TestTaskConfigurer$FinalizeTaskAction.execute(TestTaskConfigurer.java:103) |  
at org.gradle.testretry.internal.config.TestTaskConfigurer$ConditionalTaskAction.execute(TestTaskConfigurer.java:85) |  
at org.gradle.testretry.internal.config.TestTaskConfigurer$ConditionalTaskAction.execute(TestTaskConfigurer.java:72) |  
```

Looking at the class itself the relevant part looks roughly like this:

```java
public class OurTestClass extends OurTestBase {

    @BeforeClass(alwaysRun = true)
    public void beforeClass() {
       // Bunch of setup here
    }
```

**Comment by ldaley** [comment]
@deepy what version are you using?

**Comment by deepy** [comment]
@ldaley we're on test-retry-plugin 1.2.0

**Comment by ldaley** [comment]
@deepy I wasn't able to reproduce this. Can you please try to create a small reproducer that we can use. You will probably need to make your beforeClass fail.

**Comment by deepy** [comment]
I tried to make a reproducer and it fails to fail, which is great because now I got to troubleshoot a large build where it happens in about 1% of the cases 😅

**Comment by ldaley** [comment]
@deepy can you try putting a failing assert in that beforeClass in place and see what happens?

**Comment by deepy** [comment]
@ldaley both with failing assert and exceptions it retries the beforeClass successfully

**Comment by pshevche** [comment]
This seems to work with the `test-retry-plugin` 1.5.8: both if the setup fails in the parent class or in the current. The v1.5.7 of the plugin had multiple fixes related to the retrying of the class-level failures. Closing it as unreproducible for now. Feel free to re-open if this occurs again in the latest version of the plugin.
