### ISSUE TITLE
Unable to retry org.gradle.integtests.resource.gcs.ivy.IvyGcsUploadArchivesIntegrationTest#can publish using uploadArchives

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/test-retry-gradle-plugin#90]
The test retry plugin was unable to retry the test `org.gradle.integtests.resource.gcs.ivy.IvyGcsUploadArchivesIntegrationTest#can publish using uploadArchives`.

https://ge.gradle.org/s/wzyfumua24ka4

**Comment by marcphilipp** [comment]
I'm pretty sure this is caused by the same root cause as https://github.com/spockframework/spock/issues/1235.

**Comment by JLLeitschuh** [comment]
Does that have a resolution/solution?

**Comment by marcphilipp** [comment]
I'm afraid not: https://github.com/gradle/gradle/issues/15185
