### ISSUE TITLE
Not working anymore with newer Gradle versions?

### ISSUE THREAD

**Issue by pandoras-toolbox** [gradle/test-retry-gradle-plugin#99]
I tried again after many months to use your plugin. But it failed with Gradle 6.8.3.

I used it like in your examples. But Gradle tells: Extension with name 'retry' does not exist. Currently registered extension names: [ext]

**Comment by marcphilipp** [comment]
The plugin is definitely working with newer versions of Gradle. Have you applied `retry` on the top-level in your build script? Please post a more complete example.

**Comment by pandoras-toolbox** [comment]
It looks like this (excerpts) for a Gradle project with subprojects and JUnit 5 tests:

```
plugins {
    id("com.github.ben-manes.versions") version "0.38.0"
    id("io.qameta.allure") version "2.8.1"
    id("org.gradle.test-retry") version "1.2.1"
}

subprojects {
    tasks.withType<Test>().configureEach {
        retry {
            maxRetries.set(2)
        }
        useJUnitPlatform()
    }
}

```
For IntelliJ it looks fine. But when I build it it displays an error: "Extension with name 'retry' does not exist. Currently registered extension names: [ext]"

On the top level I cannot put it, it says unresolved reference.

**Comment by marcphilipp** [comment]
@pandoras-toolbox Does the above fail for you as a standalone project?

**Comment by pandoras-toolbox** [comment]
It works outside of the subprojects block. I will then configure it in the subprobjects. Although it would have been nicer if I could use it in the subprojects block, not having to repeat the code in each subproject where I want to set a retry.

**Comment by ldaley** [comment]
@pandoras-toolbox that's ultimately how Gradle configuration works and isn't a problem scoped to this plugin.

**Comment by Comnir** [comment]
@pandoras-toolbox you should be able to avoid the repetition if you use [the legacy plugin application](https://plugins.gradle.org/plugin/org.gradle.test-retry) instead of the `plugins` block.  The `buildscript` should be outside of the `subprojects` and `apply plugin` inside `subprojects` as suggested [here](https://discuss.gradle.org/t/cannot-use-plugins-block-inside-subprojects-block/13570/5).

**Comment by pandoras-toolbox** [comment]
Thank you. But now only some of the subprojects should do a retry of failing tests. So I will keep the configuration for this per subproject. But it is of course good to have both options, configure it for all subprojects or only for some subprojects.
